In [24]:
import cifar10
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import numpy as np

In [2]:
cifar10.data_path = "data/CIFAR-10/"

In [3]:
cifar10.maybe_download_and_extract()

Data has apparently already been downloaded and unpacked.


In [4]:
class_names = cifar10.load_class_names()
class_names

Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [5]:
images_train, cls_train, labels_train = cifar10.load_training_data()
images_test, cls_test, labels_test = cifar10.load_test_data()

Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch


In [6]:
labels_test

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.]])

In [7]:
cls_test

array([3, 8, 8, ..., 5, 1, 7])

In [8]:
images_test

array([[[[ 0.61960784,  0.43921569,  0.19215686],
         [ 0.62352941,  0.43529412,  0.18431373],
         [ 0.64705882,  0.45490196,  0.2       ],
         ..., 
         [ 0.5372549 ,  0.37254902,  0.14117647],
         [ 0.49411765,  0.35686275,  0.14117647],
         [ 0.45490196,  0.33333333,  0.12941176]],

        [[ 0.59607843,  0.43921569,  0.2       ],
         [ 0.59215686,  0.43137255,  0.15686275],
         [ 0.62352941,  0.44705882,  0.17647059],
         ..., 
         [ 0.53333333,  0.37254902,  0.12156863],
         [ 0.49019608,  0.35686275,  0.1254902 ],
         [ 0.46666667,  0.34509804,  0.13333333]],

        [[ 0.59215686,  0.43137255,  0.18431373],
         [ 0.59215686,  0.42745098,  0.12941176],
         [ 0.61960784,  0.43529412,  0.14117647],
         ..., 
         [ 0.54509804,  0.38431373,  0.13333333],
         [ 0.50980392,  0.37254902,  0.13333333],
         [ 0.47058824,  0.34901961,  0.12941176]],

        ..., 
        [[ 0.26666667,  0.48627451,

In [12]:
images_test.shape

(10000, 32, 32, 3)

In [15]:
images_test[0]

array([[[ 0.61960784,  0.43921569,  0.19215686],
        [ 0.62352941,  0.43529412,  0.18431373],
        [ 0.64705882,  0.45490196,  0.2       ],
        ..., 
        [ 0.5372549 ,  0.37254902,  0.14117647],
        [ 0.49411765,  0.35686275,  0.14117647],
        [ 0.45490196,  0.33333333,  0.12941176]],

       [[ 0.59607843,  0.43921569,  0.2       ],
        [ 0.59215686,  0.43137255,  0.15686275],
        [ 0.62352941,  0.44705882,  0.17647059],
        ..., 
        [ 0.53333333,  0.37254902,  0.12156863],
        [ 0.49019608,  0.35686275,  0.1254902 ],
        [ 0.46666667,  0.34509804,  0.13333333]],

       [[ 0.59215686,  0.43137255,  0.18431373],
        [ 0.59215686,  0.42745098,  0.12941176],
        [ 0.61960784,  0.43529412,  0.14117647],
        ..., 
        [ 0.54509804,  0.38431373,  0.13333333],
        [ 0.50980392,  0.37254902,  0.13333333],
        [ 0.47058824,  0.34901961,  0.12941176]],

       ..., 
       [[ 0.26666667,  0.48627451,  0.69411765],
        

In [20]:
pca=PCA()
x=images_train
y=labels_train

In [23]:
type(cls_test)

numpy.ndarray

In [27]:
np.savetxt("C:\\Users\\rawat\\Desktop\\answer.csv",cls_test, fmt='%f', delimiter=',')