In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA

In [2]:
from sklearn import datasets

In [3]:
breast_cancer=datasets.load_breast_cancer()

In [4]:
pca=PCA()
reduced=pca.fit_transform(breast_cancer.data)
pca.explained_variance_

array([4.43782605e+05, 7.31010006e+03, 7.03833742e+02, 5.46487379e+01,
       3.98900178e+01, 3.00458768e+00, 1.81533030e+00, 3.71466740e-01,
       1.55513547e-01, 8.40612196e-02, 3.16089533e-02, 7.49736514e-03,
       3.16165652e-03, 2.16150395e-03, 1.32653879e-03, 6.40269304e-04,
       3.74883320e-04, 2.35169626e-04, 1.84583467e-04, 1.64180064e-04,
       7.81102011e-05, 5.76111660e-05, 3.49172775e-05, 2.83952689e-05,
       1.61463677e-05, 1.24902419e-05, 3.68048171e-06, 2.84790425e-06,
       2.00491564e-06, 7.01997261e-07])

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler=StandardScaler()
x=scaler.fit_transform(breast_cancer.data)


In [7]:
pca=PCA()
reduced=pca.fit_transform(x)
pca.explained_variance_

array([1.33049908e+01, 5.70137460e+00, 2.82291016e+00, 1.98412752e+00,
       1.65163324e+00, 1.20948224e+00, 6.76408882e-01, 4.77456255e-01,
       4.17628782e-01, 3.51310875e-01, 2.94433153e-01, 2.61621161e-01,
       2.41782421e-01, 1.57286149e-01, 9.43006956e-02, 8.00034045e-02,
       5.95036135e-02, 5.27114222e-02, 4.95647002e-02, 3.12142606e-02,
       3.00256631e-02, 2.74877113e-02, 2.43836914e-02, 1.80867940e-02,
       1.55085271e-02, 8.19203712e-03, 6.91261258e-03, 1.59213600e-03,
       7.50121413e-04, 1.33279057e-04])

In [8]:
taken=0
total=pca.explained_variance_.sum()
k=0
while(taken/total<=0.95):
    taken+=pca.explained_variance_[k]
    k+=1
k

10

In [9]:
pca=PCA(n_components=k)
reduced=pca.fit_transform(x)
pca.explained_variance_

array([13.30499079,  5.7013746 ,  2.82291016,  1.98412752,  1.65163324,
        1.20948224,  0.67640888,  0.47745625,  0.41762878,  0.35131087])

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [16]:
cl=LogisticRegression()
x=breast_cancer.data
y=breast_cancer.target

xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=1)

scaler=StandardScaler()
x=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)

pca=PCA(n_components=k)
reduced_train=pca.fit_transform(x)
reduced_test=pca.transform(xtest)

cl.fit(reduced_train,ytrain)
cl.score(reduced_test,ytest)
#print(reduced_train)

0.972027972027972